server:
  port: 8080

spring:
  application:
    name: API_GATEWAY_ROUTER
 
  cloud:
    gateway:
      routes:
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/api/customer/**

      - id: RESTAURANT-SERVICE
        uri: lb://RESTAURANT-SERVICE
        predicates:
        - Path=/api/restaurant/**
      
      discovery:
        locator:
          enabled: true

management:
  endpoint:
    gateway:
      enabled: true 
  endpoints:
    web:
      exposure:
        include: gateway
